"""Initial Migrationale

Revision ID: 6b7db6d6d7d8
Revises: e62c1e1bfd68
Create Date: 2019-10-04 11:17:43.952562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b7db6d6d7d8'
down_revision = 'e62c1e1bfd68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.drop_column('bookings', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('bookings', 'start_date')
    # ### end Alembic commands ###
