"""Initial Migrationale

Revision ID: bd16da56b897
Revises: d1215faed01e
Create Date: 2019-10-03 20:04:16.245396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd16da56b897'
down_revision = 'd1215faed01e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('picture_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'picture_path')
    # ### end Alembic commands ###
