"""Initial Migrationale

Revision ID: e62c1e1bfd68
Revises: bd16da56b897
Create Date: 2019-10-04 11:14:03.776980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62c1e1bfd68'
down_revision = 'bd16da56b897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'date')
    # ### end Alembic commands ###
